# Generated by Django 4.2.5 on 2023-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Person',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
